PERMISSION_DEFINITIONS = {
    "ticket.create": ("Create support cases", "tickets"),
    "ticket.view_own": ("View cases created by the user", "tickets"),
    "ticket.view_assigned": ("View assigned cases", "tickets"),
    "ticket.view_team": ("View cases in the user's teams", "tickets"),
    "ticket.view_department": ("View cases in managed departments", "tickets"),
    "ticket.view_all_org": ("View all cases in the organization", "tickets"),
    "ticket.reply": ("Reply to a case", "tickets"),
    "ticket.internal_note": ("View and add internal notes", "tickets"),
    "ticket.assign": ("Assign unassigned cases", "tickets"),
    "ticket.reassign": ("Reassign cases", "tickets"),
    "ticket.change_priority": ("Change case priority", "tickets"),
    "ticket.change_status": ("Change case status", "tickets"),
    "ticket.escalate": ("Escalate cases", "tickets"),
    "ticket.resolve": ("Resolve cases", "tickets"),
    "ticket.reopen": ("Reopen eligible cases", "tickets"),
    "ticket.delete": ("Archive or delete cases", "tickets"),
    "customer.view": ("View customer profiles", "customers"),
    "customer.manage": ("Manage customer profiles", "customers"),
    "team.view": ("View teams", "teams"),
    "team.create": ("Create teams", "teams"),
    "team.manage": ("Manage teams and membership", "teams"),
    "user.view": ("View organization users", "users"),
    "user.invite": ("Invite organization users", "users"),
    "user.edit": ("Edit organization users", "users"),
    "user.deactivate": ("Deactivate organization users", "users"),
    "user.assign_role": ("Assign organization roles", "users"),
    "knowledge.read_public": ("Read customer-visible knowledge", "knowledge"),
    "knowledge.read_internal": ("Read internal knowledge", "knowledge"),
    "knowledge.create": ("Create knowledge drafts", "knowledge"),
    "knowledge.edit": ("Edit knowledge", "knowledge"),
    "knowledge.publish": ("Publish knowledge", "knowledge"),
    "knowledge.archive": ("Archive knowledge", "knowledge"),
    "document.read": ("Read permitted documents", "documents"),
    "document.manage": ("Upload, archive, and re-index documents", "documents"),
    "ai.use": ("Use AI assistance", "ai"),
    "ai.inspect_citations": ("Inspect AI citations", "ai"),
    "ai.inspect_retrieval": ("Inspect retrieval traces", "ai"),
    "ai.manage_ingestion": ("Manage ingestion and indexing", "ai"),
    "ai.manage_models": ("Manage approved models", "ai"),
    "ai.manage_prompts": ("Manage prompt policies", "ai"),
    "ai.evaluate": ("Run AI and retrieval evaluations", "ai"),
    "analytics.personal": ("View personal analytics", "analytics"),
    "analytics.team": ("View team analytics", "analytics"),
    "analytics.department": ("View department analytics", "analytics"),
    "analytics.organization": ("View organization analytics", "analytics"),
    "sla.view": ("View SLA policy and risk", "sla"),
    "sla.manage": ("Manage SLA policies", "sla"),
    "settings.organization": ("Manage organization settings", "settings"),
    "settings.security": ("Manage organization security", "settings"),
    "settings.integrations": ("Manage integrations", "settings"),
    "audit.view": ("View audit logs", "audit"),
    "billing.view": ("View billing", "billing"),
    "billing.manage": ("Manage billing", "billing"),
    "platform.manage": ("Manage the CaseMind platform", "platform"),
}


ROLE_DEFINITIONS = {
    "customer": ("Customer", "Customer support portal", {
        "ticket.create", "ticket.view_own", "ticket.reply", "ticket.reopen",
        "knowledge.read_public", "ai.use", "analytics.personal",
    }),
    "support_agent": ("Support Agent", "Assigned-case support workspace", {
        "ticket.create", "ticket.view_assigned", "ticket.view_team", "ticket.reply",
        "ticket.internal_note", "ticket.change_status", "ticket.escalate", "ticket.resolve",
        "customer.view", "team.view", "knowledge.read_public", "knowledge.read_internal",
        "ai.use", "ai.inspect_citations", "analytics.personal", "sla.view",
    }),
    "senior_agent": ("Senior Agent", "Complex-case and specialist workspace", {
        "ticket.create", "ticket.view_assigned", "ticket.view_team", "ticket.reply",
        "ticket.internal_note", "ticket.assign", "ticket.reassign", "ticket.change_priority",
        "ticket.change_status", "ticket.escalate", "ticket.resolve", "customer.view", "team.view",
        "knowledge.read_public", "knowledge.read_internal", "knowledge.create", "knowledge.edit",
        "document.read", "ai.use", "ai.inspect_citations", "analytics.personal", "analytics.team", "sla.view",
    }),
    "team_lead": ("Team Lead", "Team operations workspace", {
        "ticket.create", "ticket.view_assigned", "ticket.view_team", "ticket.reply", "ticket.internal_note",
        "ticket.assign", "ticket.reassign", "ticket.change_priority", "ticket.change_status", "ticket.escalate",
        "ticket.resolve", "customer.view", "team.view", "team.manage", "user.view",
        "knowledge.read_public", "knowledge.read_internal", "knowledge.create", "knowledge.edit", "document.read",
        "ai.use", "ai.inspect_citations", "analytics.personal", "analytics.team", "sla.view",
    }),
    "support_manager": ("Support Manager", "Support management console", {
        "ticket.create", "ticket.view_assigned", "ticket.view_team", "ticket.view_department", "ticket.view_all_org", "ticket.reply",
        "ticket.internal_note", "ticket.assign", "ticket.reassign", "ticket.change_priority", "ticket.change_status",
        "ticket.escalate", "ticket.resolve", "ticket.reopen", "customer.view", "customer.manage", "team.view",
        "team.create", "team.manage", "user.view", "knowledge.read_public", "knowledge.read_internal",
        "knowledge.create", "knowledge.edit", "knowledge.publish", "knowledge.archive", "document.read", "document.manage",
        "ai.use", "ai.inspect_citations", "analytics.personal", "analytics.team", "analytics.department",
        "analytics.organization", "sla.view", "sla.manage", "audit.view",
    }),
    "knowledge_manager": ("Knowledge Manager", "Knowledge management studio", {
        "ticket.view_department", "customer.view", "knowledge.read_public", "knowledge.read_internal",
        "knowledge.create", "knowledge.edit", "knowledge.publish", "knowledge.archive", "document.read",
        "ai.use", "ai.inspect_citations", "analytics.department",
    }),
    "ai_manager": ("AI / RAG Manager", "AI control center", {
        "ticket.view_department", "knowledge.read_public", "knowledge.read_internal", "document.read", "document.manage",
        "ai.use", "ai.inspect_citations", "ai.inspect_retrieval", "ai.manage_ingestion", "ai.manage_models",
        "ai.manage_prompts", "ai.evaluate", "analytics.department", "audit.view",
    }),
    "org_admin": ("Organization Admin", "Organization administration console", set(PERMISSION_DEFINITIONS) - {"platform.manage"}),
    "super_admin": ("Super Admin", "CaseMind platform operations", set(PERMISSION_DEFINITIONS)),
}


LEGACY_ROLE_MAP = {
    "admin": "org_admin",
    "manager": "support_manager",
    "engineer": "senior_agent",
    "product": "knowledge_manager",
    "agent": "support_agent",
    "cs": "support_agent",
    "viewer": "customer",
}


DEFAULT_WORKSPACES = {
    "customer": "customer",
    "support_agent": "agent",
    "senior_agent": "senior-agent",
    "team_lead": "team",
    "support_manager": "manager",
    "knowledge_manager": "knowledge",
    "ai_manager": "ai",
    "org_admin": "admin",
    "super_admin": "platform",
}
